export const APP_ROUTES = {
    // admin routes
    ADMIN_SIGNIN: 'admin/signin',
    ASSOCIATION: 'association',
    FEDERATION: 'federation',
    USERS: 'users',
    PERMISSION: 'permission',
    ROL: 'rol',
    CATEGORY: 'category',
    GROUP_CATEGORY: 'groupcategory',
    EVENT: 'event',
    LOCATION: 'location',
    TYPE_EVENT: 'typesevent',
    STATUS_EVENT: 'statusevent',
    DASHBOARD: "admin",
    ENTRY_CATEGORIES: 'entrycategories',
    CLASS_CATEGORIES: 'classcategories',
    ATHLETE_INSCRIPTIONS: 'athlete_inscriptions',
    NEW: 'new',
    //athlete routes
    DASHBOARD_ATHLETE: "",
    ATHLETE_SIGNIN: 'signin',
    ATHLETE_REGISTER_EVENT: 'registerevent',
    ATHLETE_ENTRYCATEGORIES: 'athlete/entrycategories',
}